import { linearizeChannel, delinearizeChannel } from "../../color-spaces/srgb";
import type { RGB } from "../../types";

/**
 * Synthetic dataset with known ground truth.
 *
 * The point of a synthetic set is that the true answer is known *exactly*, so
 * the engine's error can be measured rather than eyeballed. It simulates the
 * degradations the spec lists — illuminant casts, exposure error, noise,
 * highlights, shadows, background contamination.
 *
 * IMPORTANT — what this can and cannot prove. These images are generated by a
 * simple model of a camera, so passing on them proves the *math* is sound and
 * guards against regressions. It says nothing about real-world accuracy: a real
 * sensor has a spectral response, demosaicing, tone mapping and per-device
 * processing that this does not simulate. Any accuracy claim for the product
 * must come from the physical ColorChecker protocol in docs/COLOR_ENGINE.md,
 * never from this file.
 */

export type SyntheticCase = {
  name: string;
  /** The true color of the surface, before any camera degradation. */
  truth: RGB;
  rgba: Uint8Array;
  width: number;
  height: number;
  /** Degradations applied, for grouping benchmark results. */
  conditions: string[];
};

export type SceneOptions = {
  size?: number;
  /** Multiplicative per-channel illuminant applied in linear light. */
  illuminant?: { r: number; g: number; b: number };
  /** Exposure multiplier in linear light: <1 underexposed, >1 overexposed. */
  exposure?: number;
  /** Peak-to-peak sensor noise in 8-bit units. */
  noise?: number;
  /** Fraction of ROI pixels replaced by a specular highlight, 0–1. */
  highlights?: number;
  /** Fraction of ROI pixels darkened by a shadow, 0–1. */
  shadows?: number;
  /** Background color filling everything outside the central ROI. */
  background?: RGB;
  /** Deterministic seed. */
  seed?: number;
};

/** Deterministic PRNG so every generated case is reproducible. */
function prng(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 4294967296;
  };
}

const clampByte = (value: number) => Math.min(255, Math.max(0, Math.round(value)));

/**
 * Applies an illuminant and exposure in *linear* light, the way physics does.
 *
 * Doing this in gamma-encoded space — the tempting shortcut — would produce a
 * cast the engine could never correctly undo, and would make the whole
 * benchmark measure the wrong thing.
 */
function applyLightingToChannel(value8: number, gain: number, exposure: number): number {
  const linear = linearizeChannel(value8 / 255) * gain * exposure;
  return clampByte(delinearizeChannel(Math.min(1, Math.max(0, linear))) * 255);
}

/**
 * Renders one synthetic scene: a colored patch centered on a background, with
 * the requested degradations applied.
 */
export function renderScene(truth: RGB, options: SceneOptions = {}): SyntheticCase {
  const {
    size = 64,
    illuminant = { r: 1, g: 1, b: 1 },
    exposure = 1,
    noise = 0,
    highlights = 0,
    shadows = 0,
    background = { r: 128, g: 128, b: 128 },
    seed = 1,
  } = options;

  const random = prng(seed);
  const rgba = new Uint8Array(size * size * 4);

  // ROI is the central 40%, matching the engine's default and the on-screen
  // reticle — the patch must fill it completely.
  const roiSide = Math.round(size * 0.4);
  const roiStart = Math.floor((size - roiSide) / 2);
  // Make the patch slightly larger than the ROI so edge pixels are still the
  // subject, not background bleed.
  const patchStart = roiStart - 2;
  const patchEnd = roiStart + roiSide + 2;

  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const inPatch = x >= patchStart && x < patchEnd && y >= patchStart && y < patchEnd;
      let source = inPatch ? truth : background;

      if (inPatch) {
        const roll = random();
        if (roll < highlights) {
          // Specular highlight: mostly the light's own color, not the surface.
          source = { r: 250, g: 250, b: 250 };
        } else if (roll < highlights + shadows) {
          source = { r: source.r * 0.35, g: source.g * 0.35, b: source.b * 0.35 };
        }
      }

      const offset = (y * size + x) * 4;
      const jitter = noise === 0 ? 0 : (random() - 0.5) * noise;

      rgba[offset] = clampByte(
        applyLightingToChannel(source.r, illuminant.r, exposure) + jitter,
      );
      rgba[offset + 1] = clampByte(
        applyLightingToChannel(source.g, illuminant.g, exposure) + jitter,
      );
      rgba[offset + 2] = clampByte(
        applyLightingToChannel(source.b, illuminant.b, exposure) + jitter,
      );
      rgba[offset + 3] = 255;
    }
  }

  const conditions: string[] = [];
  if (illuminant.r !== 1 || illuminant.g !== 1 || illuminant.b !== 1) conditions.push("cast");
  if (exposure !== 1) conditions.push(exposure < 1 ? "underexposed" : "overexposed");
  if (noise > 0) conditions.push("noise");
  if (highlights > 0) conditions.push("highlights");
  if (shadows > 0) conditions.push("shadows");
  if (conditions.length === 0) conditions.push("ideal");

  return { name: "", truth, rgba, width: size, height: size, conditions };
}

/** Reference surfaces spanning the hue circle plus neutrals. */
export const TEST_SURFACES: { id: string; rgb: RGB }[] = [
  { id: "red", rgb: { r: 196, g: 48, b: 43 } },
  { id: "orange", rgb: { r: 224, g: 124, b: 36 } },
  { id: "yellow", rgb: { r: 232, g: 200, b: 52 } },
  { id: "green", rgb: { r: 64, g: 150, b: 76 } },
  { id: "cyan", rgb: { r: 60, g: 168, b: 176 } },
  { id: "blue", rgb: { r: 52, g: 88, b: 172 } },
  { id: "purple", rgb: { r: 116, g: 68, b: 156 } },
  { id: "pink", rgb: { r: 220, g: 130, b: 170 } },
  { id: "brown", rgb: { r: 124, g: 84, b: 52 } },
  { id: "light_gray", rgb: { r: 200, g: 200, b: 200 } },
  { id: "mid_gray", rgb: { r: 122, g: 122, b: 122 } },
  { id: "dark_gray", rgb: { r: 64, g: 64, b: 64 } },
];

/** Named degradation profiles, each simulating a plausible capture condition. */
export const CONDITION_PROFILES: { id: string; options: SceneOptions }[] = [
  { id: "ideal", options: {} },
  { id: "tungsten_cast", options: { illuminant: { r: 1.35, g: 1.0, b: 0.65 } } },
  { id: "shade_cast", options: { illuminant: { r: 0.82, g: 0.96, b: 1.3 } } },
  { id: "underexposed", options: { exposure: 0.45 } },
  { id: "overexposed", options: { exposure: 1.8 } },
  { id: "noisy", options: { noise: 26 } },
  { id: "specular", options: { highlights: 0.12 } },
  { id: "shadowed", options: { shadows: 0.15 } },
  {
    id: "combined",
    options: {
      illuminant: { r: 1.2, g: 1.0, b: 0.78 },
      exposure: 0.75,
      noise: 14,
      highlights: 0.06,
      shadows: 0.06,
    },
  },
];

/**
 * Builds the full dataset: every surface under every condition.
 *
 * @returns One case per (surface, condition) pair, each with a deterministic
 * seed so the benchmark is reproducible run to run.
 */
export function buildSyntheticDataset(): SyntheticCase[] {
  const cases: SyntheticCase[] = [];
  let seed = 1;

  for (const surface of TEST_SURFACES) {
    for (const profile of CONDITION_PROFILES) {
      const scene = renderScene(surface.rgb, { ...profile.options, seed: seed++ });
      cases.push({ ...scene, name: `${surface.id}/${profile.id}` });
    }
  }

  return cases;
}
